files:
  ignore:
    - '_lightbox.scss'

rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order: 0
  nesting-depth: 0
  no-duplicate-properties: 0
  single-line-per-selector: 0
  no-transition-all: 0
  quotes: 0
  no-vendor-prefixes: 0
  placeholder-in-extend: 0
