#!/bin/bash

docker stop $(docker ps -q)

docker kill kitchens
docker rm kitchens

docker build -t kitchens .

if [ -z "$APP_ENV" ]; then
    APP_ENV="prod"
fi

# if [ $APP_ENV == "dev" ]; then
#     docker run --name kitchens -p 0.0.0.0:80:80 -p 0.0.0.0:443:443 \
#         -v /Users/matthewdavies/Sites/kitchens-international/:/var/www/html \
#         -v /var/www/letsencrypt-well-known:/var/www/letsencrypt-well-known \
#         kitchens
# else
#     docker run -d --name kitchens -p 0.0.0.0:80:80 -p 0.0.0.0:443:443 \
#         -v /home/ubuntu/kitchens/:/var/www/html \
#         -v /var/www/letsencrypt-well-known:/var/www/letsencrypt-well-known \
#         kitchens
# fi

if [ $APP_ENV == "dev" ]; then
    docker run --name kitchens -p 0.0.0.0:80:80 \
        -v /Users/matthewdavies/Sites/kitchens-international/:/var/www/html \
        kitchens
else
    docker run -d --name kitchens -p 0.0.0.0:80:80 \
        -v /home/ubuntu/ki/:/var/www/html \
        kitchens
fi
