#!/bin/bash

docker stop $(docker ps -q)

docker kill ki
docker rm ki

docker build -t ki .

if [ -z "$APP_ENV" ]; then
    APP_ENV="prod"
fi

# if [ $APP_ENV == "dev" ]; then
#     docker run --name ki -p 0.0.0.0:80:80 -p 0.0.0.0:443:443 \
#         -v /Users/matthewdavies/Sites/ki/:/var/www/html \
#         -v /var/www/letsencrypt-well-known:/var/www/letsencrypt-well-known \
#         ki
# else
#     docker run -d --name ki -p 0.0.0.0:80:80 -p 0.0.0.0:443:443 \
#         -v /home/ubuntu/ki/:/var/www/html \
#         -v /var/www/letsencrypt-well-known:/var/www/letsencrypt-well-known \
#         ki
# fi

if [ $APP_ENV == "dev" ]; then
    docker run --name ki -p 0.0.0.0:80:80 \
        -v /Users/matthewdavies/Sites/kitchens-international/:/var/www/html \
        ki
else
    docker run -d --name ki -p 0.0.0.0:80:80 \
        -v /home/ubuntu/ki/:/var/www/html \
        ki
fi
